
-- Clear demo campaigns (keep any user-created ones if needed; in this demo we wipe)
DELETE FROM public.applications WHERE campaign_id IN (SELECT id FROM public.campaigns WHERE created_by IS NULL);
DELETE FROM public.campaigns WHERE created_by IS NULL;

INSERT INTO public.campaigns (brand_name, brand_logo_url, title, tagline, brief, deliverables, do_dont, platform, target_niches, target_tiers, cpv_paise, budget_inr, slots_total, slots_filled, deadline, requires_script, payout_window_days, status)
VALUES
-- HERO 12 with real Clearbit logos
('Myntra','https://logo.clearbit.com/myntra.com','Style Drops Reel — Spring Edit','Show your spring fit haul','Create a Reel showing 3 outfits from Myntra Spring collection. Tag #MyntraStyleDrop and link in bio.', ARRAY['1 Reel 30-60s','3 outfit transitions','Caption + hashtags'],'{"do":["Tag @myntra","Use trending audio","Show price tag"],"dont":["No competitor brands","No filters that hide product"]}'::jsonb,'instagram',ARRAY['fashion','lifestyle'],ARRAY['nano','micro','mid']::creator_tier[],45,50000,40,12, now()+interval '6 days', true, 7, 'active'),
('Zomato','https://logo.clearbit.com/zomato.com','Late-Night Cravings Reel','Order, unbox, devour','30s Reel of your late-night Zomato order — unboxing + first bite reaction. Use code ZOMHUNGRY.', ARRAY['1 Reel','Show app order screen','Code in caption'],'{"do":["Real reaction","Show delivery bag"],"dont":["No staged plates"]}'::jsonb,'instagram',ARRAY['food','lifestyle'],ARRAY['nano','micro','mid']::creator_tier[],55,75000,50,18, now()+interval '4 days', true, 7, 'active'),
('Swiggy','https://logo.clearbit.com/swiggy.com','Instamart 10-Min Challenge','Order in 10. Cook in 20.','Order groceries via Swiggy Instamart, cook a quick recipe, share the full reel.', ARRAY['1 Reel 45-60s','Recipe steps','Show timer'],'{"do":["Show Instamart screen"],"dont":["No outside ingredients"]}'::jsonb,'both',ARRAY['food','lifestyle','parenting'],ARRAY['nano','micro','mid','macro']::creator_tier[],60,100000,60,22, now()+interval '8 days', true, 7, 'active'),
('CRED','https://logo.clearbit.com/cred.club','Pay & Play with CRED','Show your CRED coins flex','Reel about paying credit-card bill on CRED, redeeming a reward. 30s.', ARRAY['1 Reel','Show CRED app','Reward unboxing'],'{"do":["Real card","Real reward"],"dont":["No staged screens"]}'::jsonb,'instagram',ARRAY['finance','tech','lifestyle'],ARRAY['micro','mid','macro']::creator_tier[],75,150000,30,8, now()+interval '12 hours', true, 10, 'active'),
('Mamaearth','https://logo.clearbit.com/mamaearth.in','Glow Routine Reel','7-day Mamaearth challenge','Document your 7-day skincare routine with Mamaearth Vitamin C range.', ARRAY['1 Reel','Before/after','Routine steps'],'{"do":["Natural lighting","Real skin"],"dont":["No heavy filters"]}'::jsonb,'instagram',ARRAY['beauty','lifestyle'],ARRAY['nano','micro','mid']::creator_tier[],50,80000,45,15, now()+interval '10 days', true, 7, 'active'),
('boAt','https://logo.clearbit.com/boat-lifestyle.com','Wear Your Sound — Airdopes Reel','Style + sound combo','Showcase boAt Airdopes 161 in your daily routine.', ARRAY['1 Reel','Show product 360°','Music sync'],'{"do":["Use trending audio"],"dont":["No competitor TWS"]}'::jsonb,'both',ARRAY['tech','lifestyle','fitness'],ARRAY['nano','micro','mid']::creator_tier[],45,60000,40,10, now()+interval '5 days', true, 7, 'active'),
('Nykaa','https://logo.clearbit.com/nykaa.com','Get Ready With Me — Nykaa Edit','GRWM using 5 Nykaa picks','GRWM Reel using only Nykaa products. Tag in caption.', ARRAY['1 Reel','5 product mention','Code link'],'{"do":["Real GRWM"],"dont":["No competitor brands"]}'::jsonb,'instagram',ARRAY['beauty','fashion','lifestyle'],ARRAY['nano','micro','mid','macro']::creator_tier[],55,90000,50,20, now()+interval '7 days', true, 7, 'active'),
('Cult.fit','https://logo.clearbit.com/cult.fit','Workout-from-Home Reel','Sweat with Cult','15-day Cult.fit at-home workout series — share day 1 reel.', ARRAY['1 Reel 30s','Form check','App screen'],'{"do":["Show real sweat"],"dont":["No gym footage"]}'::jsonb,'instagram',ARRAY['fitness','lifestyle'],ARRAY['nano','micro','mid']::creator_tier[],50,70000,35,11, now()+interval '6 days', true, 7, 'active'),
('Groww','https://logo.clearbit.com/groww.in','First SIP Story','Explain SIP in 60 seconds','Educational Reel: explain how to start your first SIP on Groww.', ARRAY['1 Reel 60s','Show app','Disclaimer'],'{"do":["Add SEBI disclaimer"],"dont":["No specific stock advice"]}'::jsonb,'both',ARRAY['finance','education','tech'],ARRAY['micro','mid']::creator_tier[],65,120000,30,7, now()+interval '14 days', true, 10, 'active'),
('MakeMyTrip','https://logo.clearbit.com/makemytrip.com','Long Weekend Getaway Reel','Plan it on MMT','Plan a weekend trip via MakeMyTrip — show booking + destination clips.', ARRAY['1 Reel','Booking screen','Destination clips'],'{"do":["Real booking"],"dont":["No competitor OTA"]}'::jsonb,'instagram',ARRAY['travel','lifestyle'],ARRAY['nano','micro','mid','macro']::creator_tier[],55,85000,40,14, now()+interval '9 days', true, 7, 'active'),
('Sleepy Owl','https://logo.clearbit.com/sleepyowl.co','Cold Brew Morning Reel','Brew it in 3 minutes','Quick cold brew prep with Sleepy Owl Coffee bottles.', ARRAY['1 Reel','Brewing steps','Taste reaction'],'{"do":["Show Sleepy Owl bottle"],"dont":["No instant coffee"]}'::jsonb,'instagram',ARRAY['food','lifestyle'],ARRAY['nano','micro']::creator_tier[],40,40000,30,9, now()+interval '11 days', true, 7, 'active'),
('BlueStone','https://logo.clearbit.com/bluestone.com','Everyday Gold Reel','Gold for the modern girl','Style 2 BlueStone everyday-gold pieces in a 30s lifestyle Reel.', ARRAY['1 Reel','Close-up of jewellery'],'{"do":["Natural light"],"dont":["No heavy edits"]}'::jsonb,'instagram',ARRAY['fashion','lifestyle'],ARRAY['micro','mid','macro']::creator_tier[],70,100000,25,5, now()+interval '13 days', true, 10, 'active'),

-- 38 more without external logos (BrandLogo monogram fallback)
('Acko Insurance', NULL,'Bike Insurance in 90 sec',NULL,'Quick explainer Reel about Acko 2-wheeler insurance.', ARRAY['1 Reel'],'{"do":[],"dont":[]}'::jsonb,'instagram',ARRAY['finance','automotive'],ARRAY['nano','micro']::creator_tier[],45,40000,25,4, now()+interval '7 days', true, 7,'active'),
('Lenskart', NULL,'Frame Try-On Reel',NULL,'Try 3 Lenskart frames using Home Try-On.', ARRAY['1 Reel'],'{"do":[],"dont":[]}'::jsonb,'instagram',ARRAY['fashion','lifestyle'],ARRAY['nano','micro','mid']::creator_tier[],50,60000,40,12, now()+interval '5 days', true, 7,'active'),
('boult', NULL,'Audio Drop Reel',NULL,'Showcase boult Audio TWS.', ARRAY['1 Reel'],'{}'::jsonb,'instagram',ARRAY['tech','lifestyle'],ARRAY['nano','micro']::creator_tier[],38,35000,20,5, now()+interval '10 days', true, 7,'active'),
('Plum Goodness', NULL,'Skin Diary Reel',NULL,'7-day Plum routine.', ARRAY['1 Reel'],'{}'::jsonb,'instagram',ARRAY['beauty','lifestyle'],ARRAY['nano','micro']::creator_tier[],42,45000,30,8, now()+interval '8 days', true, 7,'active'),
('Wakefit', NULL,'Best Sleep Reel',NULL,'Wakefit mattress unboxing + sleep test.', ARRAY['1 Reel'],'{}'::jsonb,'instagram',ARRAY['lifestyle','parenting'],ARRAY['micro','mid']::creator_tier[],55,70000,20,3, now()+interval '12 days', true, 7,'active'),
('Beardo', NULL,'Beard Care Reel',NULL,'Daily Beardo routine for men.', ARRAY['1 Reel'],'{}'::jsonb,'instagram',ARRAY['beauty','lifestyle'],ARRAY['nano','micro']::creator_tier[],40,38000,25,7, now()+interval '6 days', true, 7,'active'),
('Sugar Cosmetics', NULL,'Bold Lip Reel',NULL,'Try 3 SUGAR liquid lipsticks.', ARRAY['1 Reel'],'{}'::jsonb,'instagram',ARRAY['beauty','fashion'],ARRAY['nano','micro','mid']::creator_tier[],52,80000,40,15, now()+interval '9 days', true, 7,'active'),
('Mivi', NULL,'Made in India Audio Reel',NULL,'Showcase Mivi Duopods.', ARRAY['1 Reel'],'{}'::jsonb,'instagram',ARRAY['tech','lifestyle'],ARRAY['nano','micro']::creator_tier[],38,30000,20,4, now()+interval '8 days', true, 7,'active'),
('Healthify', NULL,'Calorie Track Reel',NULL,'Use Healthify Snap to log a meal.', ARRAY['1 Reel'],'{}'::jsonb,'instagram',ARRAY['fitness','food','tech'],ARRAY['micro','mid']::creator_tier[],50,55000,25,6, now()+interval '11 days', true, 7,'active'),
('Wow Skin Science', NULL,'Hair Care Reel',NULL,'Wow onion shampoo 14-day reel.', ARRAY['1 Reel'],'{}'::jsonb,'instagram',ARRAY['beauty','lifestyle'],ARRAY['nano','micro']::creator_tier[],42,42000,30,10, now()+interval '7 days', true, 7,'active'),
('Country Delight', NULL,'Fresh Milk Reel',NULL,'Country Delight unboxing morning routine.', ARRAY['1 Reel'],'{}'::jsonb,'instagram',ARRAY['food','parenting','lifestyle'],ARRAY['nano','micro']::creator_tier[],45,50000,35,11, now()+interval '6 days', true, 7,'active'),
('Boldfit', NULL,'Home Gym Reel',NULL,'Show 3 Boldfit gym equipment.', ARRAY['1 Reel'],'{}'::jsonb,'both',ARRAY['fitness','lifestyle'],ARRAY['nano','micro']::creator_tier[],40,38000,25,8, now()+interval '8 days', true, 7,'active'),
('MapMyIndia', NULL,'Smart Navigation Reel',NULL,'Use MapMyIndia for Indian routes.', ARRAY['1 Reel'],'{}'::jsonb,'both',ARRAY['tech','automotive','travel'],ARRAY['micro','mid']::creator_tier[],55,60000,20,4, now()+interval '14 days', true, 10,'active'),
('Nothing', NULL,'Phone Setup Reel',NULL,'Unbox Nothing Phone (2a) with cinematic feel.', ARRAY['1 Reel'],'{}'::jsonb,'both',ARRAY['tech','lifestyle'],ARRAY['micro','mid','macro']::creator_tier[],85,200000,15,2, now()+interval '5 days', true, 14,'active'),
('Realme', NULL,'Camera Test Reel',NULL,'Show Realme Narzo camera shots.', ARRAY['1 Reel'],'{}'::jsonb,'both',ARRAY['tech','lifestyle'],ARRAY['nano','micro','mid']::creator_tier[],50,60000,30,7, now()+interval '9 days', true, 7,'active'),
('Mokobara', NULL,'Travel Pack Reel',NULL,'Pack a Mokobara suitcase for a 4-day trip.', ARRAY['1 Reel'],'{}'::jsonb,'instagram',ARRAY['travel','lifestyle'],ARRAY['micro','mid']::creator_tier[],55,55000,15,3, now()+interval '12 days', true, 10,'active'),
('Faasos', NULL,'Wrap Lunch Reel',NULL,'Order Faasos wrap and review.', ARRAY['1 Reel'],'{}'::jsonb,'instagram',ARRAY['food'],ARRAY['nano','micro']::creator_tier[],40,30000,30,12, now()+interval '6 days', true, 7,'active'),
('Smytten', NULL,'Sample Box Reel',NULL,'Unbox the Smytten Trial Pack.', ARRAY['1 Reel'],'{}'::jsonb,'instagram',ARRAY['beauty','lifestyle'],ARRAY['nano','micro']::creator_tier[],38,28000,25,8, now()+interval '10 days', true, 7,'active'),
('Atomberg', NULL,'Smart Fan Reel',NULL,'Atomberg Renesa fan installation.', ARRAY['1 Reel'],'{}'::jsonb,'instagram',ARRAY['lifestyle','tech'],ARRAY['micro','mid']::creator_tier[],50,50000,15,2, now()+interval '11 days', true, 10,'active'),
('Ola Electric', NULL,'EV Ride Reel',NULL,'Day with Ola S1 Pro.', ARRAY['1 Reel'],'{}'::jsonb,'instagram',ARRAY['automotive','tech','lifestyle'],ARRAY['micro','mid','macro']::creator_tier[],75,150000,20,3, now()+interval '15 days', true, 14,'active'),
('Ather', NULL,'Ather 450X Review',NULL,'Ride + review the Ather 450X.', ARRAY['1 Reel'],'{}'::jsonb,'youtube',ARRAY['automotive','tech'],ARRAY['mid','macro']::creator_tier[],95,250000,10,1, now()+interval '20 days', true, 14,'active'),
('Slurrp Farm', NULL,'Healthy Kids Snack Reel',NULL,'Cook with Slurrp Farm millet.', ARRAY['1 Reel'],'{}'::jsonb,'instagram',ARRAY['parenting','food'],ARRAY['nano','micro','mid']::creator_tier[],45,40000,25,7, now()+interval '8 days', true, 7,'active'),
('Bira 91', NULL,'Chill Friday Reel',NULL,'Bira 91 lifestyle reel (21+ creators).', ARRAY['1 Reel'],'{}'::jsonb,'instagram',ARRAY['lifestyle'],ARRAY['micro','mid']::creator_tier[],55,60000,20,5, now()+interval '7 days', true, 10,'active'),
('PharmEasy', NULL,'Order Meds Reel',NULL,'Order monthly meds via PharmEasy.', ARRAY['1 Reel'],'{}'::jsonb,'instagram',ARRAY['lifestyle','parenting'],ARRAY['nano','micro']::creator_tier[],42,38000,25,6, now()+interval '9 days', true, 7,'active'),
('upGrad', NULL,'Career Story Reel',NULL,'Share your upskilling story with upGrad.', ARRAY['1 Reel'],'{}'::jsonb,'both',ARRAY['education','tech','finance'],ARRAY['micro','mid']::creator_tier[],65,100000,20,4, now()+interval '12 days', true, 10,'active'),
('Unacademy', NULL,'Study Hack Reel',NULL,'Share 3 study hacks using Unacademy.', ARRAY['1 Reel'],'{}'::jsonb,'instagram',ARRAY['education'],ARRAY['nano','micro']::creator_tier[],40,35000,30,9, now()+interval '6 days', true, 7,'active'),
('Vedantu', NULL,'Math Tip Reel',NULL,'Quick math hack reel.', ARRAY['1 Reel'],'{}'::jsonb,'instagram',ARRAY['education','parenting'],ARRAY['nano','micro']::creator_tier[],38,30000,25,5, now()+interval '8 days', true, 7,'active'),
('Skybags', NULL,'Bag Pack Reel',NULL,'Skybags pack reel.', ARRAY['1 Reel'],'{}'::jsonb,'instagram',ARRAY['travel','fashion'],ARRAY['nano','micro']::creator_tier[],38,30000,20,4, now()+interval '10 days', true, 7,'active'),
('iD Fresh Food', NULL,'Idli in 5 min Reel',NULL,'iD Fresh batter quick breakfast.', ARRAY['1 Reel'],'{}'::jsonb,'instagram',ARRAY['food','parenting'],ARRAY['nano','micro']::creator_tier[],40,35000,25,7, now()+interval '7 days', true, 7,'active'),
('Loco', NULL,'Stream Setup Reel',NULL,'Show your Loco streamer corner.', ARRAY['1 Reel'],'{}'::jsonb,'instagram',ARRAY['gaming','tech'],ARRAY['nano','micro']::creator_tier[],45,40000,20,4, now()+interval '9 days', true, 7,'active'),
('Mountain Dew', NULL,'Adventure Reel',NULL,'Outdoor adventure reel.', ARRAY['1 Reel'],'{}'::jsonb,'instagram',ARRAY['lifestyle','travel','fitness'],ARRAY['micro','mid','macro']::creator_tier[],65,100000,15,2, now()+interval '11 days', true, 10,'active'),
('Yoga Bar', NULL,'Protein Snack Reel',NULL,'Yoga Bar high-protein snack reel.', ARRAY['1 Reel'],'{}'::jsonb,'instagram',ARRAY['fitness','food'],ARRAY['nano','micro']::creator_tier[],42,40000,30,9, now()+interval '6 days', true, 7,'active'),
('OneCard', NULL,'Metal Card Reel',NULL,'Show OneCard metal credit card unboxing.', ARRAY['1 Reel'],'{}'::jsonb,'instagram',ARRAY['finance','tech','lifestyle'],ARRAY['micro','mid']::creator_tier[],70,80000,15,3, now()+interval '13 days', true, 10,'active'),
('Jio Saavn', NULL,'Playlist Drop Reel',NULL,'Share your Saavn playlist.', ARRAY['1 Reel'],'{}'::jsonb,'instagram',ARRAY['lifestyle'],ARRAY['nano','micro']::creator_tier[],35,28000,30,11, now()+interval '8 days', true, 7,'active'),
('TVS', NULL,'Ride Reel',NULL,'TVS Apache ride reel.', ARRAY['1 Reel'],'{}'::jsonb,'youtube',ARRAY['automotive'],ARRAY['micro','mid']::creator_tier[],60,75000,12,2, now()+interval '14 days', true, 10,'active'),
('Pharmeasy Diagnostics', NULL,'Health Check Reel',NULL,'Annual health check reel.', ARRAY['1 Reel'],'{}'::jsonb,'instagram',ARRAY['lifestyle','fitness','parenting'],ARRAY['nano','micro']::creator_tier[],40,35000,20,5, now()+interval '7 days', true, 7,'active');
